### ISSUE TITLE
how to verify my replay result is correct (for L0 workloads)

### ISSUE THREAD

**Issue by guoyejun** [intel/gits#4]
Hi,

I have captured my L0 workloads and replayed it without errors, but is there a way to verify that the data in the result buffer is correct? thanks.

**Comment by marekkozl** [comment]
Hi @guoyejun, you can enable buffer dumps during recording and rely on application validation - it will give you a 'reference' buffers. During playback you can compare result buffers to the reference.

**Comment by guoyejun** [comment]
thanks @marekkozl 

Which option in gits_config.yml should I use to enable the buffer dumps for L0 workloads during recording?
```
LevelZero:
  Recorder:
    Mode: 'All'  # All / Kernel
    Kernel:
      Range: '1/1/1'
    DumpKernels: '-/-/-'
    DumpAfterSubmit: false
    DumpImages: false
    DumpInputKernels: false
    BufferResetAfterCreate: false
    NullIndirectPointersInBuffer: true
    BruteForceScanForIndirectPointers:
      MemoryType: 0  # -1 (All), 1 (Host), 2 (Device), 4 (Shared)
      Iterations: 0
    DisableAddressTranslation:
      MemoryType: 0  # -1 (All) , 1 (Host), 2 (Device), 4 (Shared)
      VirtualDeviceMemorySize: 1099511627776
      VirtualHostMemorySize: 1099511627776
    DumpLayoutOnly: false

```

At playback time, does gitsPlayer automatically compare the result, or should I manually use diff-like tool to compare the result?   If the latter, how can I get the actual result buffer during playback? thanks
